server:
  port: 8085

spring:
  application:
    name: notification-service
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/signum_animae_notificationservice
    username: ${Username}
    password: ${Password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

services:
  auth-service:
    url: http://localhost:8081

internal:
  service-token: ${INTERNAL_SERVICE_TOKEN:local-dev-internal-token}
